name: sky_watch
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # The following automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0

  # local storage
  shared_preferences: ^2.0.18

  # internet connection availability
  internet_connection_checker: ^1.0.0+1

  # network calls
  dio: ^5.0.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^4.0.1
  logger: any
  json_annotation: ^4.8.0

  # state, dependency, route management, utils, properties
  get: ^4.6.5

  # dependency injection
  get_it: ^7.2.0

  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.
  dartz: ^0.10.1

  # SVG rendering and widget library which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.4

  # Decice ID/Info
  platform_device_id: ^1.0.1
  device_info_plus: ^9.0.0

  # A clean and lightweight loading/toast widget for Flutter, Easy to use without context, Support iOSã€Android and Web
  flutter_easyloading: ^3.0.5

  # Date format - Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.18.0

  # Location
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # for retrofit library
  retrofit_generator: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Thin.ttf
          weight: 200
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Medium.ttf
          weight: 500
        # - asset: assets/fonts/HelveticaNeue/HelveticaNeue-SemiBold.ttf
        #   weight: 600
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-CondensedBold.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-CondensedBlack.ttf
          weight: 900
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik/Graphik-Thin.otf
          weight: 100
        - asset: assets/fonts/Graphik/Graphik-Extralight.otf
          weight: 200
        - asset: assets/fonts/Graphik/Graphik-Light.otf
          weight: 300
        - asset: assets/fonts/Graphik/Graphik-Regular.otf
          weight: 400
        - asset: assets/fonts/Graphik/Graphik-Medium.otf
          weight: 500
        - asset: assets/fonts/Graphik/Graphik-Semibold.otf
          weight: 600
        - asset: assets/fonts/Graphik/Graphik-Bold.otf
          weight: 700
        - asset: assets/fonts/Graphik/Graphik-Black.otf
          weight: 800
        - asset: assets/fonts/Graphik/Graphik-Super.otf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
